cabal-version:      3.12
name:               pre-rich-plutus
version:            0.1.0.0
build-type:         Simple

library
    hs-source-dirs:     .
    exposed-modules:
        Types
        GameRules
        CounterValidator
        MintPolicy
        PrizePool
        PrizeValidator
        Treasury
    build-depends:
        base ^>=4.18.2,
        plutus-core ^>=1.67.0.0,
        plutus-ledger-api ^>=1.67.0.0,
        plutus-tx ^>=1.67.0.0,
        plutus-tx-plugin ^>=1.67.0.0
    default-language: Haskell2010
    ghc-options:
        -Wall
        -fno-strictness
        -fno-specialise
        -fno-spec-constr
        -fno-unbox-strict-fields
        -fno-unbox-small-strict-fields

executable export-scripts
    hs-source-dirs:     .
    main-is:            Export.hs
    other-modules:
        Types
        GameRules
        CounterValidator
        MintPolicy
        PrizePool
        PrizeValidator
        Treasury
    build-depends:
        base ^>=4.18.2,
        plutus-core ^>=1.67.0.0,
        plutus-ledger-api ^>=1.67.0.0,
        plutus-tx ^>=1.67.0.0,
        plutus-tx-plugin ^>=1.67.0.0,
        aeson,
        base16-bytestring,
        bytestring,
        directory,
        text
    default-language: Haskell2010
    ghc-options:
        -Wall
        -fno-strictness
        -fno-specialise
        -fno-spec-constr
        -fno-unbox-strict-fields
        -fno-unbox-small-strict-fields