/**
 * Carica gli script Plutus e applica i parametri alle factory.
 *
 * MintPolicy (3 params):
 *   ScriptHash counter
 *   -> ScriptHash prize
 *   -> ScriptHash registry
 *
 * PrizeValidator:
 *   ScriptHash registry
 *   -> PrizeTable
 *
 * B1PrizePool (1 param):
 *   ScriptHash prize
 */

import {
  applyParamsToScript,
  Constr,
  Data,
  type Script,
} from 'lucid-cardano'

import treasuryJson from './plutusScripts/treasury.plutus.json'
import prizeValidatorFactoryJson from './plutusScripts/prizeValidatorFactory.plutus.json'
import counterValidatorJson from './plutusScripts/counterValidator.plutus.json'
import mintPolicyFactoryJson from './plutusScripts/mintPolicyFactory.plutus.json'
// NOTE: b1PrizePoolFactory.plutus.json must be generated by running:
//   cabal run export-scripts
// The file is created by compiling B1PrizePool.compiledValidatorFactory.
// Until then, we use the old prizePool.plutus.json as a placeholder.
import b1PrizePoolFactoryJson from './plutusScripts/prizePool.plutus.json'
import beaconRegistryJson from './plutusScripts/beaconRegistry.plutus.json'

import { defaultPrizeTable, type PrizeTable } from './gameRules'

type ScriptEnvelope = {
  type: string
  description?: string
  cborHex: string
}

function toLucidScript(env: ScriptEnvelope): Script {
  return {
    type: 'PlutusV2',
    script: env.cborHex,
  }
}

const treasuryEnv = treasuryJson as ScriptEnvelope
const prizeFactoryEnv = prizeValidatorFactoryJson as ScriptEnvelope
const counterEnv = counterValidatorJson as ScriptEnvelope
const mintFactoryEnv = mintPolicyFactoryJson as ScriptEnvelope
const b1PrizePoolFactoryEnv = b1PrizePoolFactoryJson as ScriptEnvelope
const beaconRegistryEnv = beaconRegistryJson as ScriptEnvelope

/** Script senza parametri */
export const treasuryValidator = toLucidScript(treasuryEnv)
export const counterValidator = toLucidScript(counterEnv)
export const beaconRegistryValidator = toLucidScript(beaconRegistryEnv)

/** Factory grezze */
export const mintPolicyFactory = toLucidScript(mintFactoryEnv)
export const prizeValidatorFactory = toLucidScript(prizeFactoryEnv)
export const b1PrizePoolFactory = toLucidScript(b1PrizePoolFactoryEnv)

/**
 * @deprecated Preferisci buildMintPolicy(...).
 */
export const mintPolicyScript = mintPolicyFactory

/**
 * @deprecated Preferisci buildPrizeValidator(...).
 */
export const prizeValidator = prizeValidatorFactory

/**
 * PrizeTable Plutus:
 * Constr 0 [tier1, tier2, tier3, tier4, tier5]
 */
export function prizeTableToData(
  table: PrizeTable = defaultPrizeTable
): Data {
  return new Constr(0, [
    BigInt(table.tier1),
    BigInt(table.tier2),
    BigInt(table.tier3),
    BigInt(table.tier4),
    BigInt(table.tier5),
  ])
}

/**
 * Applica i 3 parametri alla MintPolicy factory.
 *
 * B1: no salePkh/priceLovelace — payment goes to Treasury, not personal wallet.
 *
 * Ordine:
 *   counterHash
 *   prizeHash
 *   registryHash
 */
export function buildMintPolicy(
  counterScriptHashHex: string,
  prizeScriptHashHex: string,
  registryScriptHashHex: string,
): Script {
  const applied = applyParamsToScript(mintFactoryEnv.cborHex, [
    counterScriptHashHex,
    prizeScriptHashHex,
    registryScriptHashHex,
  ])

  return {
    type: 'PlutusV2',
    script: applied,
  }
}

/**
 * Applica i 3 parametri alla PrizeValidator factory.
 *
 * Ordine:
 *   registryHash
 *   prizePoolHash (B1PrizePool ScriptHash)
 *   PrizeTable
 */
export function buildPrizeValidator(
  registryScriptHashHex: string,
  prizePoolScriptHashHex: string,
  table: PrizeTable = defaultPrizeTable
): Script {
  const applied = applyParamsToScript(prizeFactoryEnv.cborHex, [
    registryScriptHashHex,
    prizePoolScriptHashHex,
    prizeTableToData(table),
  ])

  return {
    type: 'PlutusV2',
    script: applied,
  }
}

/**
 * Applica 1 parametro alla B1PrizePool factory.
 *
 * Ordine:
 *   prizeHash (ScriptHash del PrizeValidator)
 */
export function buildB1PrizePool(
  prizeScriptHashHex: string
): Script {
  const applied = applyParamsToScript(b1PrizePoolFactoryEnv.cborHex, [
    prizeScriptHashHex,
  ])

  return {
    type: 'PlutusV2',
    script: applied,
  }
}

/**
 * Costruisce tutti gli script parametrizzati a partire da una
 * istanza Lucid.
 *
 * Ordine (risolve la dipendenza circolare PrizeValidator <-> B1PrizePool):
 *   1. hash del CounterValidator
 *   2. hash del BeaconRegistryValidator
 *   3. Convergenza iterativa: b1ppHash <-> prizeHash (1-2 iterazioni)
 *   4. PrizeValidator(registryHash, b1ppHash, PrizeTable)
 *   5. hash del PrizeValidator parametrizzato
 *   6. MintPolicy(counterHash, prizeHash, registryHash)
 *   7. B1PrizePool(prizeHash) — script completo
 */
export function buildScriptsFromLucid(
  lucid: {
    utils: {
      validatorToScriptHash: (script: Script) => string
      mintingPolicyToId?: (script: Script) => string
      validatorToAddress?: (script: Script) => string
    }
  },
  table: PrizeTable = defaultPrizeTable
) {
  const counterHash =
    lucid.utils.validatorToScriptHash(counterValidator)

  const registryHash =
    lucid.utils.validatorToScriptHash(beaconRegistryValidator)

  // Resolve circular dependency: PrizeValidator needs b1ppHash,
  // B1PrizePool needs prizeHash. Both are deterministic script hashes.
  // Iterate until convergence (typically 1 iteration).
  let b1ppHash = counterHash
  for (let i = 0; i < 3; i++) {
    const pv = buildPrizeValidator(registryHash, b1ppHash, table)
    const ph = lucid.utils.validatorToScriptHash(pv)
    const bh = lucid.utils.validatorToScriptHash(buildB1PrizePool(ph))
    if (bh === b1ppHash) break
    b1ppHash = bh
  }

  const prizeValidator =
    buildPrizeValidator(
      registryHash,
      b1ppHash,
      table
    )

  const prizeHash =
    lucid.utils.validatorToScriptHash(prizeValidator)

  const mintPolicy =
    buildMintPolicy(
      counterHash,
      prizeHash,
      registryHash,
    )

  const b1PrizePool =
    buildB1PrizePool(
      prizeHash,
    )

  const ticketPolicyId =
    typeof lucid.utils.mintingPolicyToId === 'function'
      ? lucid.utils.mintingPolicyToId(mintPolicy)
      : lucid.utils.validatorToScriptHash(mintPolicy)

  const counterAddress =
    typeof lucid.utils.validatorToAddress === 'function'
      ? lucid.utils.validatorToAddress(counterValidator)
      : undefined

  const registryAddress =
    typeof lucid.utils.validatorToAddress === 'function'
      ? lucid.utils.validatorToAddress(beaconRegistryValidator)
      : undefined

  const prizeAddress =
    typeof lucid.utils.validatorToAddress === 'function'
      ? lucid.utils.validatorToAddress(prizeValidator)
      : undefined

  const b1PrizePoolAddress =
    typeof lucid.utils.validatorToAddress === 'function'
      ? lucid.utils.validatorToAddress(b1PrizePool)
      : undefined

  return {
    counterHash,
    registryHash,
    prizeHash,
    b1PrizePoolHash: b1ppHash,

    mintPolicy,
    prizeValidator,
    b1PrizePool,

    ticketPolicyId,

    counterAddress,
    registryAddress,
    prizeAddress,
    b1PrizePoolAddress,
  }
}

export default {
  treasuryValidator,
  counterValidator,
  beaconRegistryValidator,

  mintPolicyFactory,
  prizeValidatorFactory,
  b1PrizePoolFactory,

  buildMintPolicy,
  buildPrizeValidator,
  buildB1PrizePool,
  buildScriptsFromLucid,
  prizeTableToData,
}
