import type {
  CanonicalCheckpoint
} from "./verifier.js";

import type {
  TrustedAuthorityState
} from "./authority.js";

export interface MateriosTestVector {
  name: string;

  checkpoint: CanonicalCheckpoint;

  trustedAuthorityState:
    TrustedAuthorityState;

  /*
   * Raw SCALE bytes of GrandpaJustification.
   *
   * This MUST come from an actual Materios node.
   */
  justificationHex: string;

  /*
   * Expected localized payloads generated by Rust.
   *
   * One entry per SignedPrecommit.
   */
  expectedLocalizedPayloadsHex: string[];

  expectedVerified: boolean;
}
